/** Nama aturan dalam bahasa biasa, untuk notifikasi dan dashboard. */
export const RULE_LABELS: Record<string, string> = {
  R1: 'customer di kasir tanpa order',
  R2: 'void setelah pesanan diproduksi',
  R3: 'void setelah customer pergi',
  R4: 'sensor/printer berhenti mengirim data',
  R5: 'kertas habis berkepanjangan',
  R5B: 'klaim kertas habis tidak sesuai printer',
  R6: 'makan karyawan di luar kuota atau untuk diri sendiri',
  R7: 'pembayaran non-tunai tidak ada di bank',
  R8: 'nominal bank lebih kecil dari POS',
  R9: 'EDC/TID tidak sesuai registri outlet',
  R10: 'selisih total harian tidak terjelaskan',
  R11: 'void kasir hampir selalu disetujui orang yang sama',
  R12: 'kasir menyimpang jauh dari rekannya (void, refund, diskon, cetak ulang)',
  R13: 'void dan ganti metode bayar menumpuk saat kertas habis',
  R14: 'selisih kas berulang saat tutup shift',
  R15: 'stok fisik kurang dari pemakaian menurut resep (bahan bernilai)',
  R16: 'pemakaian gulungan kertas jauh di atas cetakan yang tercatat',
  R17: 'laci kas dibuka tanpa pembayaran tunai',
  R19: 'QR statis dipakai padahal EDC atau QR dinamis tersedia',
  R20: 'cetak ulang dan pindah meja menumpuk menjelang tutup shift',
  R18: 'diskon setelah bill dicetak',
  R21: 'refund tanpa customer',
  R22: 'metode bayar diubah setelah lunas',
  R23: 'diskon manual besar tanpa verifikasi',
  R24: 'integritas data perangkat',
  R25: 'order tanpa presence berulang',
  R26: 'transaksi bank tanpa pembayaran POS',
  R27: 'total settlement EDC berbeda dengan POS',
  R28: 'metode bayar di POS tidak sesuai settlement',
  R29: 'pengaturan keamanan perangkat kasir tidak aman',
  R42: 'transaksi oleh staf yang tidak sedang absen',
  R43: 'pembayaran dengan uang muka reservasi yang tidak sah',
  R44: 'uang muka reservasi belum dipertanggungjawabkan lebih dari 24 jam',
  R45: 'pesanan web diterima tetapi tidak jadi order kasir, atau tautannya tidak sah',
  R46: 'order kasir dari pesanan web di-void atau tidak dibayar',
  R47: 'order dari pesanan web dibayar jauh di bawah nilainya',
  R48: 'antrian dipanggil melewati tiket yang lebih lama menunggu',
  R49: 'tamu dari antrian didudukkan tanpa order kasir yang sah',
  R50: 'harga beli jauh di atas supplier lain untuk bahan yang sama',
  R51: 'harga faktur supplier di atas harga pesanan',
  R52: 'resep atau BOM dikurangi tak lama setelah selisih stok',
  R53: 'koreksi absen berulang untuk staf yang sama',
  R40: 'transfer stok antar-outlet belum diterima lebih dari 24 jam',
  R41: 'transfer stok diterima kurang dari yang dikirim',
  R37: 'pesanan online di POS tidak ada di laporan platform',
  R38: 'nilai pesanan online di POS berbeda dari laporan platform',
  R39: 'pesanan dibayar platform tetapi tidak ada di POS',
  R35: 'pembayaran platform tidak cocok dengan kaitan pesanan online',
  R36: 'nomor pesanan platform dipakai lebih dari satu order',
  R33: 'penukaran poin member tidak wajar (saldo kurang, member tidak dikenal, atau member berbeda)',
  R34: 'satu member dikaitkan ke terlalu banyak order dalam sehari',
  R32: 'diskon promo tidak sesuai aturan promo di server',
  R31: 'order dipindahkan antar-terminal di luar serah-terima',
  R30: 'kas yang seharusnya dilaporkan terminal tidak sama dengan hitungan server',
};

export const ruleLabel = (rule: string): string => RULE_LABELS[rule] ?? rule;
